//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ПрактикаБД
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Practic_restEntities1 : DbContext
    {
        public Practic_restEntities1()
            : base("name=Practic_restEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cooker> Cooker { get; set; }
        public virtual DbSet<Eat> Eat { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Viewsi> Viewsi { get; set; }
    }
}
