//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ПрактикаБД
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int ID_menu { get; set; }
        public int Eats_ID { get; set; }
        public int Cookers_ID { get; set; }
        public string Enable { get; set; }
    
        public virtual Cooker Cooker { get; set; }
        public virtual Eat Eat { get; set; }
    }
}
