//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ПрактикаБД
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viewsi
    {
        public string Блюдо { get; set; }
        public int Цена { get; set; }
        public string Имя_повара { get; set; }
        public string Фамилия_повара { get; set; }
        public string Отчество_повара { get; set; }
        public string Доступность { get; set; }
    }
}
